basePath: /api/v1
definitions:
  controllers._ResponseData:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/controllers.ResCode'
        description: 业务响应状态码
      data:
        description: 数据
      message:
        description: 提示信息
        type: string
    type: object
  controllers._ResponsePostData:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/controllers.ResCode'
        description: 业务响应状态码
      data:
        allOf:
        - $ref: '#/definitions/models.ApiPostDetail'
        description: 单个帖子数据
      message:
        description: 提示信息
        type: string
    type: object
  controllers._ResponsePostList:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/controllers.ResCode'
        description: 业务响应状态码
      data:
        description: 帖子列表数据
        items:
          $ref: '#/definitions/models.ApiPostDetail'
        type: array
      message:
        description: 提示信息
        type: string
    type: object
  controllers.ResCode:
    enum:
    - 1000
    - 1001
    - 1002
    - 1003
    - 1004
    - 1005
    - 1006
    - 1007
    format: int64
    type: integer
    x-enum-varnames:
    - CodeSuccess
    - CodeInvalidParam
    - CodeUserExist
    - CodeUserNoteExist
    - CodeInvalidPassword
    - CodeServeBusy
    - CodeInvalidToken
    - CodeNeedLogin
  models.ApiPostDetail:
    properties:
      author_id:
        type: integer
      author_name:
        type: string
      community:
        allOf:
        - $ref: '#/definitions/models.CommunityDetail'
        description: 嵌入社区信息
      community_id:
        type: integer
      content:
        type: string
      create_time:
        type: string
      id:
        type: integer
      status:
        type: integer
      title:
        type: string
      votes:
        type: integer
    required:
    - community_id
    - content
    - title
    type: object
  models.CommunityDetail:
    properties:
      create_time:
        description: 连接mysql时要加上parseTime=true
        type: string
      id:
        type: integer
      introduction:
        type: string
      name:
        type: string
    type: object
  models.ParaLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.ParaSignUp:
    properties:
      password:
        type: string
      re_password:
        type: string
      username:
        type: string
    required:
    - password
    - re_password
    - username
    type: object
  models.ParaVoteData:
    properties:
      direction:
        description: 赞成票 1 反对票-1 取消投票0 required会把0值过滤 所以删掉required
        enum:
        - 1
        - 0
        - -1
        example: "0"
        type: string
      post_id:
        description: UserID 从请求中获取当前的用户  不用从结构体
        type: string
    required:
    - post_id
    type: object
  models.Post:
    properties:
      author_id:
        type: integer
      community_id:
        type: integer
      content:
        type: string
      create_time:
        type: string
      id:
        type: integer
      status:
        type: integer
      title:
        type: string
    required:
    - community_id
    - content
    - title
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: 张政的第一个完整的golang项目
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Bluebell_Zhang_Zheng
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.ParaLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 用户登录接口
      tags:
      - 用户相关接口
  /post:
    post:
      consumes:
      - application/json
      description: 创建帖子接口
      parameters:
      - description: 帖子参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 创建帖子接口
      tags:
      - 帖子相关接口
  /post/{id}:
    get:
      consumes:
      - application/json
      description: 获取单个帖子详情接口
      parameters:
      - description: 帖子id
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponsePostData'
      security:
      - ApiKeyAuth: []
      summary: 获取单个帖子详情接口
      tags:
      - 帖子相关接口
  /posts:
    get:
      consumes:
      - application/json
      description: 获取一页帖子详情的接口(已弃用)
      parameters:
      - description: 页码
        in: query
        name: page
        required: true
        type: integer
      - description: 每页大小
        in: query
        name: size
        required: true
        type: integer
      - description: 排序方式
        in: query
        name: order
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 获取一页帖子详情的接口(已弃用)
      tags:
      - 帖子相关接口
  /posts2:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 可以为空
        in: query
        name: community_id
        type: integer
      - description: 排序依据
        example: score
        in: query
        name: order
        type: string
      - description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 每页数据量
        example: 10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 升级版帖子列表接口
      tags:
      - 帖子相关接口
  /signup:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 注册参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ParaSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1000, "msg":"success", "data":null}'
          schema:
            $ref: '#/definitions/controllers._ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 用户注册接口
      tags:
      - 用户相关接口
  /vote:
    post:
      consumes:
      - application/json
      description: 投票接口
      parameters:
      - description: 投票参数
        in: body
        name: object
        schema:
          $ref: '#/definitions/models.ParaVoteData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers._ResponseData'
      security:
      - ApiKeyAuth: []
      summary: 投票接口
      tags:
      - 帖子相关接口
swagger: "2.0"
